name: generate-openvpn-china-routes.yml
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/setup-node@v3
          with:
            node-version: 18.x
        - run: echo node -v
